name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/backtick-base-app:latest,${{ secrets.DOCKER_REGISTRY_USERNAME }}/backtick-base-app:${{ github.ref_name }}
      # - name: Deploy a new version
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.SERVER_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       docker pull ${{ secrets.DOCKER_REGISTRY_USERNAME }}/backtick-base-app:latest &&
      #       docker stop backtick-base-app &&
      #       docker container rm backtick-base-app || true &&
      #       docker run -d -p 3000:3000 --name backtick-base-app -e NODE_ENV=production -e PORT=3000 -e APP_ENV=production -e SCOPES=write_products -e SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }} -e SHOPIFY_API_SECRET=${{ secrets.SHOPIFY_API_SECRET }} -e SHOPIFY_APP_URL=${{ secrets.SHOPIFY_APP_URL }} mrbacktick/backtick-base-app:latest;
